# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('aed', models.DecimalField(decimal_places=10, max_digits=19)),
                ('bnd', models.DecimalField(decimal_places=10, max_digits=19)),
                ('brl', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cad', models.DecimalField(decimal_places=10, max_digits=19)),
                ('clp', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cop', models.DecimalField(decimal_places=10, max_digits=19)),
                ('egp', models.DecimalField(decimal_places=10, max_digits=19)),
                ('irr', models.DecimalField(decimal_places=10, max_digits=19)),
                ('jpy', models.DecimalField(decimal_places=10, max_digits=19)),
                ('krw', models.DecimalField(decimal_places=10, max_digits=19)),
                ('mmk', models.DecimalField(decimal_places=10, max_digits=19)),
                ('nzd', models.DecimalField(decimal_places=10, max_digits=19)),
                ('pkr', models.DecimalField(decimal_places=10, max_digits=19)),
                ('qar', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rub', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sar', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sgd', models.DecimalField(decimal_places=10, max_digits=19)),
                ('syp', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ttd', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
