# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20160926_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='cad',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='clp',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='cop',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='egp',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='irr',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='jpy',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='krw',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='mmk',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='nzd',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pkr',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='qar',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='sar',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='sgd',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='syp',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ttd',
        ),
        migrations.AlterField(
            model_name='currency',
            name='aed',
            field=models.DecimalField(decimal_places=10, default=3.76, max_digits=19),
        ),
        migrations.AlterField(
            model_name='currency',
            name='bnd',
            field=models.DecimalField(decimal_places=10, default=1.41, max_digits=19),
        ),
        migrations.AlterField(
            model_name='currency',
            name='brl',
            field=models.DecimalField(decimal_places=10, default=3.98, max_digits=19),
        ),
    ]
