# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20160926_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
