# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_currency_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='prediction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
