# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20160926_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='eur',
            field=models.DecimalField(decimal_places=2, default=0.79, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='idr',
            field=models.DecimalField(decimal_places=2, default=300.39, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='inr',
            field=models.DecimalField(decimal_places=2, default=7.39, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='irr',
            field=models.DecimalField(decimal_places=2, default=58.39, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='isk',
            field=models.DecimalField(decimal_places=2, default=2.22, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='mmk',
            field=models.DecimalField(decimal_places=2, default=4.39, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='nzd',
            field=models.DecimalField(decimal_places=2, default=45.9, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='omr',
            field=models.DecimalField(decimal_places=2, default=5.39, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='pkr',
            field=models.DecimalField(decimal_places=2, default=21.39, max_digits=19),
        ),
    ]
