# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20160926_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='qar',
            field=models.DecimalField(decimal_places=2, default=34.35, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='rub',
            field=models.DecimalField(decimal_places=2, default=63.36, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='syp',
            field=models.DecimalField(decimal_places=2, default=213.75, max_digits=19),
        ),
        migrations.AddField(
            model_name='currency',
            name='technique',
            field=models.CharField(choices=[('SVM', 'Svm'), ('MLP', 'Mlp'), ('DT', 'DecicionTree')], default='MLP', max_length=3),
        ),
        migrations.AddField(
            model_name='currency',
            name='vnd',
            field=models.DecimalField(decimal_places=2, default=22311.47, max_digits=19),
        ),
        migrations.AlterField(
            model_name='currency',
            name='idr',
            field=models.DecimalField(decimal_places=2, default=13031.5, max_digits=19),
        ),
    ]
